# Generated by Django 6.0.5 on 2026-05-05 23:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fr', models.CharField(default='À propos de Lugayetu', max_length=255)),
                ('title_en', models.CharField(default='About Lugayetu', max_length=255)),
                ('description_fr', models.TextField(default='Lugayetu est un projet scientifique et culturel dédié à la préservation, la documentation et la valorisation des langues en danger de la République Démocratique du Congo.')),
                ('description_en', models.TextField(default='Lugayetu is a scientific and cultural project dedicated to the preservation, documentation, and promotion of endangered languages in the Democratic Republic of Congo.')),
                ('mission_title_fr', models.CharField(default='Notre mission', max_length=255)),
                ('mission_title_en', models.CharField(default='Our mission', max_length=255)),
                ('mission_text_fr', models.TextField(default="Collecter et archiver la richesse linguistique congolaise avant qu'elle ne disparaisse, en permettant aux locuteurs natifs d'enregistrer leur voix et de contribuer à un corpus unique de langues menacées.")),
                ('mission_text_en', models.TextField(default='Collect and archive the Congolese linguistic wealth before it disappears, allowing native speakers to record their voice and contribute to a unique corpus of endangered languages.')),
                ('vision_title_fr', models.CharField(default='Notre vision', max_length=255)),
                ('vision_title_en', models.CharField(default='Our vision', max_length=255)),
                ('vision_text_fr', models.TextField(default='Créer une bibliothèque vivante des langues congolaises accessible aux chercheurs, aux éducateurs et aux générations futures.')),
                ('vision_text_en', models.TextField(default='Create a living library of Congolese languages accessible to researchers, educators, and future generations.')),
                ('why_title_fr', models.CharField(default='Pourquoi Lugayetu ?', max_length=255)),
                ('why_title_en', models.CharField(default='Why Lugayetu?', max_length=255)),
                ('why_text_fr', models.TextField(default="La RDC compte plus de 200 langues, dont plusieurs risquent de disparaître. Chaque langue qui s'éteint emporte avec elle une culture, une histoire et une vision unique du monde. Lugayetu veut inverser cette tendance.")),
                ('why_text_en', models.TextField(default='The DRC has more than 200 languages, many of which are in danger of disappearing. Each language that dies takes with it a culture, a history, and a unique worldview. Lugayetu aims to reverse this trend.')),
                ('team_title_fr', models.CharField(default='Notre équipe', max_length=255)),
                ('team_title_en', models.CharField(default='Our team', max_length=255)),
                ('team_text_fr', models.TextField(default="Le projet est porté par des linguistes, des développeurs et des passionnés de la culture congolaise, avec le soutien d'institutions académiques et culturelles.")),
                ('team_text_en', models.TextField(default='The project is led by linguists, developers, and lovers of Congolese culture, with the support of academic and cultural institutions.')),
                ('contact_title_fr', models.CharField(default='Contact', max_length=255)),
                ('contact_title_en', models.CharField(default='Contact', max_length=255)),
                ('contact_email', models.CharField(default='eliezermunung@outlook.fr', max_length=255)),
                ('footer_message_fr', models.CharField(default='Merci de contribuer à la préservation du patrimoine linguistique congolais !', max_length=255)),
                ('footer_message_en', models.CharField(default='Thank you for contributing to the preservation of the Congolese linguistic heritage!', max_length=255)),
                ('quote_fr', models.TextField(default="Perdre sa langue, c'est perdre sa boussole culturelle.")),
                ('quote_en', models.TextField(default="To lose one's language is to lose one's cultural compass.")),
                ('history_title_fr', models.CharField(default='Notre parcours', max_length=255)),
                ('history_title_en', models.CharField(default='Our journey', max_length=255)),
                ('history_json', models.JSONField(default=list, help_text="List of objects with 'year', 'title', 'text' (fr/en keys)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu Page À propos',
                'verbose_name_plural': 'Contenus Page À propos',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_title_fr', models.CharField(default='Préserver les voix de notre héritage', max_length=255)),
                ('hero_title_en', models.CharField(default='Preserving the voices of our heritage', max_length=255)),
                ('hero_description_fr', models.TextField(default='Nous collectons et numérisons les richesses linguistiques de la RDC. Du Rund au Kikongo, redonnons vie à chaque mot pour les générations futures.')),
                ('hero_description_en', models.TextField(default="We collect and digitize the linguistic wealth of the DRC. From Rund to Kikongo, let's bring every word back to life for future generations.")),
                ('stats_title_fr', models.CharField(default='Statistiques de préservation', max_length=255)),
                ('stats_title_en', models.CharField(default='Preservation Statistics', max_length=255)),
                ('stats_description_fr', models.TextField(default='Chaque jour, nos contributeurs documentent des dialectes menacés pour assurer la pérennité de notre culture commune.')),
                ('stats_description_en', models.TextField(default='Every day, our contributors document endangered dialects to ensure the sustainability of our common culture.')),
                ('mission_title_fr', models.CharField(default='Notre Mission', max_length=255)),
                ('mission_title_en', models.CharField(default='Our Mission', max_length=255)),
                ('cta_title_fr', models.CharField(default="Prêt à faire partie de l'histoire ?", max_length=255)),
                ('cta_title_en', models.CharField(default='Ready to be part of history?', max_length=255)),
                ('cta_description_fr', models.TextField(default="Chaque mot que vous partagez aujourd'hui est un cadeau pour les générations de demain. Rejoignez notre communauté de gardiens du savoir.")),
                ('cta_description_en', models.TextField(default="Every word you share today is a gift for tomorrow's generations. Join our community of knowledge keepers.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Contenu Page d'Accueil",
                'verbose_name_plural': "Contenus Page d'Accueil",
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la langue')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code ISO/Interne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('privacy', 'Politique de Confidentialité'), ('terms', "Conditions d'Utilisation"), ('legal', 'Mentions Légales')], help_text='Identifiant technique de la page', unique=True)),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Titre (EN)')),
                ('content_fr', models.TextField(help_text='Utilisez des balises HTML pour la structure : <br><b>&lt;h3&gt;</b> Titre de section <br><b>&lt;p&gt;</b> Paragraphe <br><b>&lt;ul&gt;&lt;li&gt;</b> Listes <br><b>&lt;strong&gt;</b> Texte important', verbose_name='Contenu (FR)')),
                ('content_en', models.TextField(help_text='Use HTML tags for structure: <br><b>&lt;h3&gt;</b> Section Title <br><b>&lt;p&gt;</b> Paragraph <br><b>&lt;ul&gt;&lt;li&gt;</b> Lists <br><b>&lt;strong&gt;</b> Important text', verbose_name='Contenu (EN)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Légale',
                'verbose_name_plural': 'Pages Légales',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)], verbose_name='Âge')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True, verbose_name='Sexe')),
                ('province', models.CharField(blank=True, choices=[('bas_uele', 'Bas-Uele'), ('equateur', 'Équateur'), ('haut_katanga', 'Haut-Katanga'), ('haut_lomami', 'Haut-Lomami'), ('haut_uele', 'Haut-Uele'), ('ituri', 'Ituri'), ('kasai', 'Kasaï'), ('kasai_central', 'Kasaï-Central'), ('kasai_oriental', 'Kasaï-Oriental'), ('kinshasa', 'Kinshasa'), ('kongo_central', 'Kongo-Central'), ('kwango', 'Kwango'), ('kwilu', 'Kwilu'), ('lomami', 'Lomami'), ('lualaba', 'Lualaba'), ('mai_ndombe', 'Mai-Ndombe'), ('maniema', 'Maniema'), ('mongala', 'Mongala'), ('nord_kivu', 'Nord-Kivu'), ('nord_ubangi', 'Nord-Ubangi'), ('sankuru', 'Sankuru'), ('sud_kivu', 'Sud-Kivu'), ('sud_ubangi', 'Sud-Ubangi'), ('tanganyika', 'Tanganyika'), ('tshopo', 'Tshopo'), ('tshuapa', 'Tshuapa')], max_length=50, null=True, verbose_name='Province')),
                ('city_village', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville / Village')),
                ('role', models.CharField(choices=[('CONTRIBUTOR', 'Contributeur'), ('SUB_ADMIN', 'Sous-Admin'), ('ADMIN', 'Administrateur')], default='CONTRIBUTOR', max_length=20, verbose_name='Rôle')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('mother_tongue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_speakers', to='core.language', verbose_name='Langue maternelle')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
