# Generated by Django 6.0.5 on 2026-05-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_native', models.TextField(verbose_name='Phrase originale')),
                ('phrase_translation', models.TextField(verbose_name='Traduction (Français)')),
                ('audio_file', models.FileField(upload_to='audio/temp/', verbose_name='Fichier audio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_contributions', to='core.language', verbose_name='Langue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
            ],
            options={
                'verbose_name': 'Contribution Audio',
                'verbose_name_plural': 'Contributions Audio',
            },
        ),
        migrations.CreateModel(
            name='ContributionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_native', models.TextField(verbose_name='Phrase originale')),
                ('phrase_french', models.TextField(verbose_name='Phrase en Français')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contributions', to='core.language', verbose_name='Langue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
            ],
            options={
                'verbose_name': 'Contribution Texte',
                'verbose_name_plural': 'Contributions Texte',
            },
        ),
    ]
